apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-node-firefox 
  labels:
    app: selenium-node-firefox
  namespace: demo
spec:
  replicas: 1
  selector:
    app: selenium-node-firefox
  template:
    metadata:
      labels:
        app: selenium-node-firefox
    spec:
      containers:
      - name: selenium-node-firefox
        image: selenium/node-firefox
#        ports:
#          - containerPort: 5900 
        env:
          - name: HUB_PORT_4444_TCP_ADDR 
            value: "selenium-hub"
          - name: HUB_PORT_4444_TCP_PORT 
            value: "4444"
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"
